name: Process Delivery Note

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  process-dn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pdfplumber google-api-python-client google-auth

      - name: Run Delivery Note Processor
        run: |
          python process_dn.py
